### ISSUE TITLE
Question about path preview vs CSV file

### ISSUE THREAD

**Issue by RodrigoDomingues18** [Wayzata/FRC-2021-Trajectory-Following-Main-Bot#2]
Hi there. I have a question about your csv file from the slalom path and its preview image shown in the video. You have a lot more waypoints in the file than 'steps' shown. Can you explain why? Did you do the csv by yourself and then feed it to the bot? Was it with help of MPController or PID? Shouldn't the steps shown in the preview  of the canvas be enough to create a path and then with the controller, would self correct the robot?

**Comment by jackarivera** [comment]
The csvs were generated with an old version of Pathplanner. This repo is outdated. Do not use this as a reference

**Comment by RodrigoDomingues18** [comment]
Do you have an updated version? I'm trying to develop a very similar solution to this with a 4 mecanum wheel robot that executes a path pre defined by a user. With a defined way of moviment: (straight line + 360 ) , arcs, diagonal straight moviment (...). I wanted to know how you calculate this different types of moviments from setpoint to setpoint or if it's managed by a WPILib code snippet, provide me the location to it, because I just can't find it
